services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - elasticsearch-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    networks:
      - elasticsearch-net

  arkime:
    image: ghcr.io/mosajjal/arkime-container:v5.0.1
    container_name: arkime
    environment:
      - ARKIME_PCAPREADMETHOD=pcap-over-ip-server
      - ARKIME_BPF= # without emptying out the bpf option, pcap-over-ip does not work
      - ARKIME_TCPSAVETIMEOUT=60
      - ARKIME_OFFLINEDISPATCHAFTER=1
      - ARKIME_VIEWURL=http://0.0.0.0:8005
      - ARKIME_VIEWHOST=0.0.0.0
      - ARKIME_USERAUTHIPS=0.0.0.0/0
    command: ["--passwordSecret=Passw0rd", "--elasticsearch=http://elasticsearch-node1:9200", "--interface=dummy", "--createAdminUser=true", "--skipTlsVerifiction", "--dropUser=root", "--manufURL=https://www.wireshark.org/download/automated/data/manuf"]
    ports:
      - 8005:8005
      - 57012:57012
    depends_on:
      elasticsearch-node1:
        condition: service_healthy
    volumes:
      - ./arkime-data:/opt/arkime/raw
    networks:
      - elasticsearch-net

volumes:
  elasticsearch-data1:

networks:
  elasticsearch-net:
