name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run:  go get -v 
      working-directory: "."

    - name: Build
      run: go build -v -o arkime-container .
      working-directory: "./"

    - name: Test
      run: go test -v .
      working-directory: "."

    - name: generate sample config file 
      run: ./arkime-container --writeConfig=config.ini
      working-directory: "."

    - name: update README command line options
      run: |
        stty -F /dev/tty cols 120
        START="$(($(grep -n "start of command line options" README.md | cut -f1 -d:)+2))"
        END="$(($(grep -n "end of command line options" README.md | cut -f1 -d:)-2))"
        USAGE=$(cat <<-END
        $(COLUMNS=120 ./arkime-container --help | sed -r 1d)
        END
        )
        awk -v var="$USAGE" 'NR=='$START'{print var} NR<'$START' || NR>'$END README.md > README.tmp
        mv README.tmp README.md
      working-directory: "."
      shell: bash
      env:
        COLUMNS: 150

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Ali Mosajjal
        author_email: mosajjal@gmail.com
        message: "auto update readme and config.ini"
        add: "config.ini README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  